---
# NOTE: I am using [`hacc-ozmo`](https://github.com/Ligio/hacc-ozmo) rather than
# the [official integration](https://www.home-assistant.io/integrations/ecovacs).
# See https://github.com/home-assistant/core/issues/38625 for some additional context.
deebot:
  username: !secret 'ecovacs.username'
  password: !secret 'ecovacs.password'
  country: 'AU'
  continent: 'WW'
  unsupported_features:
    - 'fan_speed'

automation:
  - alias: 'Vacuum Error'
    id: '10a065f5-f820-42d7-aa54-ceae3e8a4993'
    mode: 'parallel'
    max: 5
    trigger:
      platform: 'event'
      event_type: 'ecovacs_error'
      event_data:
        entity_id: 'vacuum.deebot'
    condition:
      condition: 'template'
      value_template: '{{ trigger.event.data.error not in ("battery_low", "no_error") }}'
    variables:
      error_messages:
        debotsig: 'The robot is trapped. Please set it free.'
        host_hang: 'The robot is off the floor.'
        no_dust_box: 'Dust Bin not installed.'
        wheel_abnormal: 'Operating difficulties encountered. Please check the Driving Wheel.'
    action:
      service: 'script.mobile_app_notify'
      data:
        target: 'josh_phone'
        title: '{{ state_attr("vacuum.deebot", "friendly_name") }} has experienced an error'
        message: >-
          {% set error_code = trigger.event.data.error %}
          {{ error_messages[error_code] if error_code in error_messages else 'An unknown error occurred (' ~ error_code ~ ').' }}
    trace:
      stored_traces: 20
